
CREATE TABLE  STUDENTS (
  ID INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  age INTEGER NOT NULL,
  address TEXT NOT NULL
);


INSERT INTO STUDENTS  VALUES (0001, 'Иван',18,'Москва');
INSERT INTO STUDENTS  VALUES (0002, 'Ирина',23,'Тверь');
INSERT INTO STUDENTS  VALUES (0003, 'Геннфдий', 14,'Тула');
INSERT INTO STUDENTS  VALUES (0004, 'Миша', 85,'Рязань');
INSERT INTO STUDENTS VALUES (0005, 'Галя', 19,'Москва');
INSERT INTO STUDENTS VALUES (0006, 'Иван',44,'Воронеж');
INSERT INTO STUDENTS  VALUES (0007, 'Яна', 24,'Костома');
INSERT INTO STUDENTS  VALUES (0008, 'Рэм', 34,'Москва');
INSERT INTO STUDENTS  VALUES (0009, 'Николай', 12,'Мурманск');
INSERT INTO STUDENTS VALUES (0010, 'Кристина', 67,'Москва');

SELECT * FROM STUDENTS WHERE  address ='Москва';
